[local]
localhost ansible_connection=local

[production]
production-server ansible_host=178.128.93.188 ansible_user=root ansible_port=22

[laravel-servers:children]
local
production

[laravel-servers:vars]
ansible_user=jenkins
app_path=/var/www/html
deploy_user=www-data
domain_name=laravel.178.128.93.188
